import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from '../src/server.js';
import { config } from '../src/config.js';
import { db } from '../src/db.js';

test('serves health and analysis endpoints', async (t) => {
  const server=createServer();
  await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise((resolve)=>server.close(resolve)));
  const {port}=server.address();
  const health=await fetch(`http://127.0.0.1:${port}/health`).then((r)=>r.json());
  assert.equal(health.status,'ok');
  const response=await fetch(`http://127.0.0.1:${port}/api/v1/listings/1/analysis`);
  assert.equal(response.status,200);
  const analysis=await response.json();
  assert.equal(analysis.data.pricePerSqm,24078);
  const dashboard=await fetch(`http://127.0.0.1:${port}/api/v1/dashboard`).then((r)=>r.json());
  assert.ok(dashboard.data.summary.sales>=1);
  assert.ok(dashboard.data.summary.rentals>=3);
  assert.ok(dashboard.data.listings.length>=1);
  assert.equal(dashboard.data.summary.activeSources,5);
  assert.ok(dashboard.data.sources.some((source)=>source.id==='madlan'&&source.enabled));
  const seededListing=dashboard.data.listings.find((item)=>item.street==='המעגל');
  assert.equal(seededListing.latitude,32.0486091);
  const html=await fetch(`http://127.0.0.1:${port}/`).then((r)=>r.text());
  assert.match(html,/MAOR Property Intelligence/);
  assert.match(html,/propertyMap/);
  assert.match(html,/priceChart/);
  const charts=await fetch(`http://127.0.0.1:${port}/api/v1/listings/1/charts`).then((r)=>r.json());
  assert.equal(charts.data.priceHistory.length,2);
  assert.ok(charts.data.rentalComps.length>=3);
  assert.deepEqual(charts.data.yields.map((item)=>item.label),['ברוטו','נטו']);
  const alertsResponse=await fetch(`http://127.0.0.1:${port}/api/v1/alerts?unread=true`);
  assert.equal(alertsResponse.status,200);
  const sources=await fetch(`http://127.0.0.1:${port}/api/v1/sources`).then((r)=>r.json());
  assert.ok(sources.data.sources.some((source)=>source.id==='homeless'&&source.status==='ready'));
  assert.ok(sources.data.sources.some((source)=>source.id==='komo'&&source.status==='ready'&&source.collector==='direct-html'));
  assert.ok(sources.data.sources.some((source)=>source.id==='ad'&&source.aggregator));
  assert.ok(sources.data.sources.some((source)=>source.id==='facebook_marketplace_manual'&&source.status==='manual'));
  assert.ok(sources.data.sources.some((source)=>source.id==='tax_authority'&&source.status==='manual'));
  assert.ok(sources.data.sources.some((source)=>source.id==='govmap'&&source.status==='manual'));
  const ocr=await fetch(`http://127.0.0.1:${port}/api/v1/marketplace-ocr/parse`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'קריית אונו 4 חדרים 100 מ״ר ₪ 2,400,000'})}).then((r)=>r.json());
  assert.equal(ocr.data.price,2400000);assert.equal(ocr.data.rooms,4);
  const govMap=await fetch(`http://127.0.0.1:${port}/api/v1/listings/1/govmap-link`).then((r)=>r.json());
  assert.match(govMap.data.url,/govmap\.gov\.il/);
  const candidates=await fetch(`http://127.0.0.1:${port}/api/v1/listings/1/cross-source-candidates`).then((r)=>r.json());
  assert.ok(Array.isArray(candidates.data));
  const marketplaceResponse=await fetch(`http://127.0.0.1:${port}/api/v1/marketplace-inbox`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({listingType:'sale',city:'קריית אונו',street:'רחוב בדיקת API',price:2450000,rooms:4,areaSqm:100})});
  assert.equal(marketplaceResponse.status,201);
  const marketplace=await marketplaceResponse.json(),marketplaceId=marketplace.data.listingId;
  t.after(()=>{const row=db.prepare('SELECT property_id FROM listings WHERE id=?').get(marketplaceId);if(!row)return;db.prepare('DELETE FROM marketplace_inbox_items WHERE listing_id=?').run(marketplaceId);db.prepare('DELETE FROM listing_match_candidates WHERE listing_id_a=? OR listing_id_b=?').run(marketplaceId,marketplaceId);db.prepare('DELETE FROM alerts WHERE listing_id=?').run(marketplaceId);db.prepare('DELETE FROM listing_price_history WHERE listing_id=?').run(marketplaceId);db.prepare('DELETE FROM listings WHERE id=?').run(marketplaceId);db.prepare('DELETE FROM properties WHERE id=? AND NOT EXISTS(SELECT 1 FROM listings WHERE property_id=?)').run(row.property_id,row.property_id)});
  assert.ok(Array.isArray(marketplace.data.matches));
  const originalScanKey=config.scanApiKey; config.scanApiKey='protected-test-key';
  const protectedScan=await fetch(`http://127.0.0.1:${port}/api/v1/jobs/scan`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});
  config.scanApiKey=originalScanKey;
  assert.equal(protectedScan.status,401);
});
